version: '3.8'
services:
  echoserver:
    container_name: echoserver
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/data/certs:/etc/nginx/certs

  echoworks:
    container_name: echoworks
    restart: always
    build: ./
    environment:
      - PORT=8001

  echo:
    build: ./echo
    container_name: echo
    restart: always
    environment:
      - PORT=4000
    command: 'npm run start'